export const lightColors = {
  background: "#f0f2f5",
  primary: "#512DA8",
  text: "black",
  error: "#D32F2F",
  borderBottomColor: "lightgrey",
  containerColor: "white",
  listIconColor: "#F5F5F9",
  listIconBgColor: "#00478d",
  chevronColor: "black",
  activityIndicatorColor: "#f0f2f5",
  activityIndicatorBgColor: "#f0f2f5",
  homeHeader: "white",
  tabBarBgColor: "white",
  tabBarActiveColor: "#00478d",
  fabBgColor: "#e4e6ea",
  fabColor: "black",
  headerText: "#00478d",
};

// Dark theme colors
export const darkColors = {
  background: "black",
  primary: "#B39DDB",
  text: "white",
  error: "#EF9A9A",
  borderBottomColor: "#323232",
  containerColor: "#212121",
  listIconColor: "#212121",
  listIconBgColor: "#F5F5F9",
  chevronColor: "white",
  activityIndicatorColor: "#C88D36",
  activityIndicatorBgColor: "black",
  homeHeader: "black",
  tabBarBgColor: "black",
  tabBarActiveColor: "#C88D36",
  fabBgColor: "#212121",
  fabColor: "white",
  headerText: "white",
};
